"use Client";

import { Inter } from "next/font/google";
import { ClerkProvider } from "@clerk/nextjs";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Note AI",
  description: "customized flashcards using AI for instant revisions",
  title: "Create Next App",
  description: "Generated by create next app",
